language: python
python:
- '2.7'
install:
- pip install --no-deps peep --find-links https://pyrepo.addons.mozilla.org/
- peep install --no-deps -r requirements/test.txt --find-links https://pyrepo.addons.mozilla.org/
before_script:
- flake8 . --exclude=./docs/conf.py
script: ./manage.py test --noinput -s
notifications:
  irc:
    channels:
    - irc.mozilla.org#payments
    on_success: change
    on_failure: always
